# -*- coding: utf-8 -*-
"""Football_predictor.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1JUgM670W1iSCShHuvGPWnJnoj3jyX69o
"""

pip install pgmpy networkx matplotlib pandas numpy seaborn scikit-learn

# Import necessary libraries
import pandas as pd
import numpy as np
import seaborn as sns
import matplotlib.pyplot as plt
from sklearn.preprocessing import KBinsDiscretizer
from sklearn.model_selection import train_test_split
from sklearn.metrics import accuracy_score, classification_report, confusion_matrix

from pgmpy.models import BayesianNetwork
from pgmpy.estimators import MaximumLikelihoodEstimator
from pgmpy.inference import VariableElimination

import warnings
warnings.filterwarnings('ignore')

# Load datasets
games_df = pd.read_csv("games.csv")
teamstats_df = pd.read_csv("teamstats.csv")
shots_df = pd.read_csv("shots.csv")

print("✅ Datasets Loaded Successfully")

# Fill missing assisterID with 0 (assuming NA means no assist)
shots_df["assisterID"] = shots_df["assisterID"].replace("NA", np.nan).fillna(0)

# Fill missing numerical values with median
for col in teamstats_df.select_dtypes(include=[np.number]).columns:
    teamstats_df[col].fillna(teamstats_df[col].median(), inplace=True)

# Fill missing categorical values with "Unknown"
teamstats_df["location"].fillna("Unknown", inplace=True)

print("✅ Missing Values Handled")

# Encode match results: W = 1, D = 0, L = -1
label_map = {"W": 1, "D": 0, "L": -1}
teamstats_df["result"] = teamstats_df["result"].map(label_map)

# Convert date to datetime format
teamstats_df["date"] = pd.to_datetime(teamstats_df["date"])

# Rolling averages for last 5 matches (form-based features)
teamstats_df.sort_values(by=["teamID", "date"], inplace=True)
for stat in ["xGoals", "shots", "shotsOnTarget"]:
    teamstats_df[f"{stat}_rolling5"] = (
        teamstats_df.groupby("teamID")[stat].rolling(5, min_periods=1).mean().reset_index(level=0, drop=True)
    )

# Create Home/Away Feature
teamstats_df["is_home"] = (teamstats_df["location"] == "h").astype(int)

print("✅ Feature Engineering Completed")

# Select features to be used in the model
features = ["xGoals_rolling5", "shots_rolling5", "shotsOnTarget_rolling5", "is_home"]
X = teamstats_df[features]
y = teamstats_df["result"]

# Discretize continuous features into 3 bins (low, medium, high)
discretizer = KBinsDiscretizer(n_bins=2, encode="ordinal", strategy="uniform")
X_discrete = pd.DataFrame(discretizer.fit_transform(X), columns=features)
X_discrete["result"] = y.values

X_discrete = X_discrete.fillna(0)

print("✅ Data Discretized for Bayesian Network")

# Define Bayesian Network Structure
edges = [
    ("xGoals_rolling5", "result"),
    ("shots_rolling5", "result"),
    ("shotsOnTarget_rolling5", "result"),
    ("is_home", "result")
]

model = BayesianNetwork(edges)

print("✅ Bayesian Network Structure Defined")

# Fit the Bayesian Network
model.fit(X_discrete, estimator=MaximumLikelihoodEstimator)

# Initialize inference engine
inference = VariableElimination(model)

print("✅ Bayesian Network Trained Successfully")

# Split dataset into train & test
X_train, X_test, y_train, y_test = train_test_split(
    X_discrete.drop(columns=["result"]),  # Features
    X_discrete["result"],  # Target variable
    test_size=0.2, random_state=42
)

print("✅ Dataset Split into Train & Test")

import networkx as nx

# Convert Bayesian Network to a Graph
G = nx.DiGraph()
G.add_edges_from(model.edges())

# Check if there's a cycle in the graph
if nx.is_directed_acyclic_graph(G):
    print("✅ The Bayesian Network has NO cycles.")
else:
    print("❌ ERROR: The Bayesian Network contains a cycle! Fix the structure.")

# Function for batch inference with debugging and efficiency improvements
def batch_predict(inference, X_test):
    predictions = []
    total_rows = len(X_test)

    for i, row in X_test.iterrows():
        try:
            evidence = {col: int(row[col]) for col in X_test.columns}
        except ValueError as ve:
            print(f"⚠️ ValueError at row {i+1}: {ve}. Skipping row.")
            predictions.append(0)  # Assign default class and continue
            continue

        try:
            result = inference.map_query(variables=["result"], evidence=evidence, show_progress=False)
            predictions.append(result["result"])
        except Exception as e:
            print(f"❌ ERROR at row {i+1}: {e}")
            predictions.append(0)  # Default class if inference fails

        # Debugging: Print progress every 100 rows
        if (i + 1) % 100 == 0:
            print(f"✅ Processed {i+1}/{total_rows} rows")

    return predictions

# Run inference on test data
print("🚀 Running Bayesian Inference on Test Data...")
predictions = batch_predict(inference, X_test)

# Evaluate Model Performance
print("\n📊 Model Performance:")
print(classification_report(y_test, predictions))
print("Confusion Matrix:\n", confusion_matrix(y_test, predictions))
print("Accuracy:", accuracy_score(y_test, predictions))

print("✅ Model Evaluation Completed")

import networkx as nx
import matplotlib.pyplot as plt

# Create a graph from Bayesian network structure
G = nx.DiGraph()
G.add_edges_from(edges)

# Draw the Bayesian network
plt.figure(figsize=(8, 6))
pos = nx.spring_layout(G, seed=42)
nx.draw(G, pos, with_labels=True, node_size=3000, node_color="skyblue", edge_color="black", linewidths=1, font_size=12)
plt.title("Bayesian Network Structure")
plt.show()

print("✅ Bayesian Network Visualization Complete")

from sklearn.naive_bayes import GaussianNB
from sklearn.preprocessing import StandardScaler
from sklearn.model_selection import train_test_split
from sklearn.metrics import accuracy_score, classification_report, confusion_matrix

# Step 1: Merge teamstats with games on gameID first
merged_df = teamstats_df.merge(games_df, on='gameID', how='inner')
print("After merge on gameID: merged_df shape =", merged_df.shape)

# Step 2: Fix filtering using 'h' and 'a' for home/away
merged_df = merged_df[
    ((merged_df['location'] == 'h') & (merged_df['teamID'] == merged_df['homeTeamID'])) |
    ((merged_df['location'] == 'a') & (merged_df['teamID'] == merged_df['awayTeamID']))
]
print("After correct home/away filtering: merged_df shape =", merged_df.shape)

# Step 3: Define features and target
features = ['xGoals', 'shotsOnTarget', 'deep', 'ppda']
target = 'result'

# Check for NaNs
print("Missing rows before dropna:", merged_df[features + [target]].isnull().sum())

# Step 4: Drop rows with missing values
merged_df = merged_df.dropna(subset=features + [target])
print("After dropna: merged_df shape =", merged_df.shape)

# Step 5: Create X and y
X = merged_df[features]
y = merged_df[target]

print("X shape:", X.shape)
print("y shape:", y.shape)

# Step 6: Standardize
scaler = StandardScaler()
X_scaled = scaler.fit_transform(X)
print("X_scaled shape:", X_scaled.shape)

# Step 7: Split the data
X_train, X_test, y_train, y_test = train_test_split(X_scaled, y, test_size=0.2, random_state=42)
print("X_train shape:", X_train.shape, "X_test shape:", X_test.shape)

# Step 8: Train Naive Bayes model
nb_model = GaussianNB()
nb_model.fit(X_train, y_train)

# Step 9: Predictions and Evaluation
y_pred = nb_model.predict(X_test)
print("Naive Bayes Accuracy:", accuracy_score(y_test, y_pred))
print("Confusion Matrix:\n", confusion_matrix(y_test, y_pred))
print("Classification Report:\n", classification_report(y_test, y_pred))

from sklearn.naive_bayes import GaussianNB
from sklearn.preprocessing import StandardScaler
from sklearn.model_selection import train_test_split
from sklearn.metrics import accuracy_score, classification_report, confusion_matrix

# Step 1: Merge teamstats with games on gameID
merged_df = teamstats_df.merge(games_df, on='gameID', how='inner')
print("After merge on gameID: merged_df shape =", merged_df.shape)

# Step 2: Filter using correct home/away logic with 'h' and 'a'
merged_df = merged_df[
    ((merged_df['location'] == 'h') & (merged_df['teamID'] == merged_df['homeTeamID'])) |
    ((merged_df['location'] == 'a') & (merged_df['teamID'] == merged_df['awayTeamID']))
]
print("After correct home/away filtering: merged_df shape =", merged_df.shape)

# Step 3: Define features and target (added 'shots')
features = ['xGoals', 'shotsOnTarget', 'shots', 'deep', 'ppda']
target = 'result'

# Check for NaNs
print("Missing rows before dropna:", merged_df[features + [target]].isnull().sum())

# Step 4: Drop rows with missing values
merged_df = merged_df.dropna(subset=features + [target])
print("After dropna: merged_df shape =", merged_df.shape)

# Step 5: Create X and y
X = merged_df[features]
y = merged_df[target]

print("X shape:", X.shape)
print("y shape:", y.shape)

# Step 6: Standardize features
scaler = StandardScaler()
X_scaled = scaler.fit_transform(X)
print("X_scaled shape:", X_scaled.shape)

# Step 7: Train/test split
X_train, X_test, y_train, y_test = train_test_split(X_scaled, y, test_size=0.2, random_state=42)
print("X_train shape:", X_train.shape, "X_test shape:", X_test.shape)

# Step 8: Train Naive Bayes model
nb_model = GaussianNB()
nb_model.fit(X_train, y_train)

# Step 9: Predictions and Evaluation
y_pred = nb_model.predict(X_test)
print("Naive Bayes Accuracy:", accuracy_score(y_test, y_pred))
print("Confusion Matrix:\n", confusion_matrix(y_test, y_pred))
print("Classification Report:\n", classification_report(y_test, y_pred))

!pip install hmmlearn

from hmmlearn import hmm
import numpy as np
from sklearn.preprocessing import StandardScaler
from sklearn.metrics import accuracy_score, classification_report
from scipy.stats import mode

# Step 1: Merge teamstats with games on gameID
merged_df = teamstats_df.merge(games_df, on='gameID', how='inner')
print("After merge on gameID: merged_df shape =", merged_df.shape)

# Step 2: Fix merged date column after merge
if 'date_x' in merged_df.columns:
    merged_df['date'] = merged_df['date_x']
elif 'date_y' in merged_df.columns:
    merged_df['date'] = merged_df['date_y']

# Step 3: Filter using correct home/away logic
merged_df = merged_df[
    ((merged_df['location'] == 'h') & (merged_df['teamID'] == merged_df['homeTeamID'])) |
    ((merged_df['location'] == 'a') & (merged_df['teamID'] == merged_df['awayTeamID']))
]
print("After correct home/away filtering: merged_df shape =", merged_df.shape)

# Step 4: Sort by team + date (to build sequences)
merged_df['date'] = pd.to_datetime(merged_df['date'])
merged_df = merged_df.sort_values(by=['teamID', 'date'])

# Step 5: Select features and target
features = ['xGoals', 'shotsOnTarget', 'deep', 'ppda']
target = 'result'

# Drop missing rows
merged_df = merged_df.dropna(subset=features + [target])

# Step 6: Standardize features
scaler = StandardScaler()
merged_df[features] = scaler.fit_transform(merged_df[features])

# Step 7: Group by team to build sequences
team_sequences = []
team_targets = []

for team_id, group in merged_df.groupby('teamID'):
    X_seq = group[features].values
    y_seq = group[target].values
    if len(X_seq) >= 5:  # Only take teams with enough matches
        team_sequences.append(X_seq)
        team_targets.append(y_seq)

# Step 8: Concatenate all sequences for HMM fitting
X_concat = np.concatenate(team_sequences)
lengths = [len(seq) for seq in team_sequences]

# Step 9: Train Gaussian HMM
model = hmm.GaussianHMM(n_components=3, covariance_type="diag", n_iter=100)
model.fit(X_concat, lengths)

# Step 10: Predict hidden states for each team sequence
hidden_states = []
for seq in team_sequences:
    states = model.predict(seq)
    hidden_states.append(states)

# Step 11: Map hidden states to actual results using majority vote
flattened_targets = np.concatenate(team_targets)
flattened_states = np.concatenate(hidden_states)

state_to_result = {}
for s in np.unique(flattened_states):
    idx = np.where(flattened_states == s)[0]
    if len(idx) > 0:
        common_result = mode(flattened_targets[idx], keepdims=True)[0][0]
        state_to_result[s] = common_result

# Step 12: Predict based on hidden state mapping
predictions = [state_to_result[s] for s in flattened_states]

# Step 13: Evaluation
print("HMM Accuracy:", accuracy_score(flattened_targets, predictions))
print("Classification Report:\n", classification_report(flattened_targets, predictions))

from sklearn.metrics import ConfusionMatrixDisplay
import matplotlib.pyplot as plt

ConfusionMatrixDisplay.from_predictions(flattened_targets, predictions)
plt.title("Confusion Matrix - HMM Predictions")
plt.show()

import seaborn as sns

plt.figure(figsize=(6,4))
sns.heatmap(model.transmat_, annot=True, cmap='Blues', fmt='.2f')
plt.title("HMM State Transition Matrix")
plt.xlabel("To State")
plt.ylabel("From State")
plt.show()

plt.figure(figsize=(12,4))
plt.plot(flattened_states[:300], label="HMM Hidden States")
plt.plot(flattened_targets[:300], label="Actual Results", alpha=0.7)
plt.legend()
plt.title("Hidden State vs Actual Results (Sample Sample)")
plt.xlabel("Match Sequence Index")
plt.ylabel("State / Result")
plt.show()